---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
# Excel 后面才用，但写在前面比较好
library(readxl)
# SAS
library(haven)
```

## Read in some data

read in the litters dataset

```{r}

litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
spec(litters_df)
```

## take a look at the data

printing in the console.

```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
# check tail 以防数据末端异常
```

```{r}
# ::等同于library。现实中不怎么用
skimr::skim(litters_df)
# 经常用的是View(litters_df)，直接在console里写！！！
# ?read_csv可以在help里查看
```


## options to read_csv

check out `?read_csv()` for more information.
```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

## other file format

read in excel file

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
# 写在console！！！
#> View(mlb_df)
#> ?read_excel
```

read in a SAS file

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

